
# PICO SDK 位置
set(PICO_SDK_PATH   "${THIRDPARTY_PREFIX}/pico-sdk")

# PICO TOOLCHAIN 路径 自行设置
#set(PICO_TOOLCHAIN_PATH "")

# PICO SDK INIT CMAKE 位置
set(PICO_SDK_INIT_CMAKE_FILE ${PICO_SDK_PATH}/pico_sdk_init.cmake)

# 设置USB连接超时时间, 避免LOG信息丢失
if (NOT DEFINED PICO_STDIO_USB_CONNECT_WAIT_TIMEOUT_MS)
    set(PICO_STDIO_USB_CONNECT_WAIT_TIMEOUT_MS 3000)
endif()

include(${PICO_SDK_INIT_CMAKE_FILE})

